Connect api
Lusindiso/bookstore-react pull request #4
Opened 2022-08-19 08:33 UTC by Lusindiso

### In this PR I have made the following changes
- Create an action creator to fetch, send and delete data from the API,
- Connect the API with the API and process incoming data.

2022-08-19 10:04 UTC, BenMukebo requested changes
### Hi @Lusindiso,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- GitHub flow was correctly used.  ✔️   
- The *Add book* and *remove book* work the same as before ✔️ 
- Your design is awesome ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] I would recommend adding the issue link in the contributing sections:

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).

```


- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 10:04 UTC, BenMukebo commented on src/components/pages/Books.js
> +/* eslint-disable guard-for-in */
- [ ] It is always a good practice to make sure you fix all linter errors instead of disabling them, Linter is a tool for identifying and reporting errors when you use standard rules. Kindly get used to fixing liner errors manually instead of disabling it 👍🏻

2022-08-19 10:04 UTC, BenMukebo commented on src/redux/books/books.js
> +/* eslint-disable no-param-reassign */
- [ ] It is always a good practice to make sure you fix all linter errors instead of disabling them, Linter is a tool for identifying and reporting errors when you use standard rules. Kindly get used to fixing liner errors manually instead of disabling it 👍🏻

2022-08-19 10:04 UTC, BenMukebo commented on src/redux/books/booksActions.js
> +
- [ ] According to the project requirements, You were asked to Use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) or [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) for making API calls. Kindly make sure the `createAsyncThunk` is used in the project for creating thunk action creators:

```js
// This code is just an example, you can create this method in different ways.

import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios'; 


export const getBooks = createAsyncThunk(
  'books/getBooks',
  async () => {
    const response = await axios.get(
      'https://us-central1-bookstore-api-e63c8.cloudfunctions.net/bookstoreApi/',
    );
    return response.data;
  },
); 
```

2022-08-20 12:58 UTC, ShoiraTa approved these changes
Hi @Lusindiso ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 12:58 UTC, ShoiraTa commented on src/components/pages/Books.js
> +/* eslint-disable guard-for-in */
- [ ] As the previous reviewer requested, please try to fix all linter errors instead of disabling them.

2022-08-20 13:15 UTC, mirouhml approved these changes
# APPROVED 🟢

Hi @Lusindiso, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e471p9juygtcaesd615kgxa3b2n2dt6xyrzcycnk4b3&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 13:22 UTC, merged